### ISSUE TITLE
Copyright issue

### ISSUE THREAD

**Issue by fabrizioschiavi** [ghballiet/pebble-essential-simple#1]
I’m the designer and owner of the rights of Essential PragmataPro
Please remove asap the font files of your repository 
https://github.com/ghballiet/pebble-essential-simple/tree/master/resources/src/fonts
Thanks!

Fabrizio Schiavi
https://www.fsd.it/shop/fonts/pragmatapro/

**Comment by ghballiet** [comment]
My fault - this is from many years ago - I will remove this immediately!

**Comment by ghballiet** [comment]
https://github.com/ghballiet/pebble-essential-simple/commit/889aa32930255bec8d0740d8a9134febb62c971a

**Comment by fabrizioschiavi** [comment]
Thank you!
